config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  resources :posts do
    resources :comments, shallow: true
  end

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commenter, foreign_key: :user_id, class_name: 'User'
  belongs_to :post
  validates  :commenter, :post, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, foreign_key: :user_id, class_name: 'User'
  has_many   :comments
  validates :author, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, :last_name, presence: true
  has_many :posts
  has_many :comments

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.json { render partial: 'comment',locals: {comment: @comment}, status: :created, location: @comment }
      else
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:post_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params[:comment][:user_id] ||= current_user.id if params[:comment]
      params.require(:comment).permit(:body, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @author = @post.author
    @comments = @post.comments.eager_load(:commenter)
  end

  # GET /posts/new
  def new
    @post = Post.new
    @author = current_user
    @comments = Comment.none
    render :show
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params[:post][:user_id] ||= current_user.id if params[:post]
      params.require(:post).permit(:title, :body, :user_id)

    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
  def account_update_params
    sign_up_params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.slim
dt
  =comment.commenter.name
  .smaller=comment.created_at.strftime("%b %-d, %Y")
dd=comment.body

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='container-fluid'>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/posts/_post.slim
a href="/posts/#{post.id}"
  dt
    =post.author.name
    .smaller=post.created_at.strftime("%b %-d, %Y")
  dd=post.title

app/views/posts/index.html.slim
p#notice= notice
h1 Listing Posts
dl.dl-horizontal
  =render @posts.order(created_at: :desc)
br
= link_to 'New Post', new_post_path

app/views/posts/show.html.slim
=link_to 'Index', posts_path
form.post
  h5
    =@author.name
    .small =@post.updated_at.try(:strftime,"%b %-d, %Y")
  .form-group
    label Title
    input#title value=@post.title disabled=(@post.id.present?) name='title'
  .form-group
    textarea#body disabled=(@post.id.present?) name='body' =@post.body
  input#id type='hidden' value=@post.id name='id'
  button#edit =@post.id.present? ? 'Edit' : 'Save'
  button class=(@post.id.nil? ? 'hidden' : '')
    =link_to('Destroy', @post, method: :delete, data: {confirm: 'Are you sure?'})
  button class=(@post.id.present? ? 'hidden' : '')
    =link_to 'Cancel', posts_path
dl.dl-horizontal#comments
  =render @comments.order(created_at: :asc)
  dd.hidden#new
    input
button#newComment class=(@post.id.nil? ? 'hidden' : '') New Comment